### ISSUE TITLE
Actually a question: Can you show me an example implementation?

### ISSUE THREAD

**Issue by DeadSix27** [danielrichman/namecheap-api#1]
I was trying to create a basic IPv6 DynDNS client using curl, but I fail at 

`{"Result":null,"Error":true,"Msg":"A required anti-forgery token was not supplied or was invalid","Errors":null,"MsgType":0}`

But if your script can handle such token's It would be just what I need, but its a little over my head so a Example implementation would be quite nice to see.

(As I can't even find any login/cookie re-usage in your code, so I wonder how that is handled)

**Comment by danielrichman** [comment]
Added example.py in dec026f. Does that help?

**Comment by DeadSix27** [comment]
I'll give it a try later and report back, thanks for the example :)!

EDIT: Alright, it works fine :)! I could successfully use the cookie I get by using my CURL script in your python code, thanks for your help!
